id: A932F7CCC
base_file: f46BE.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:10:28.028650
  last_modified_at: 2022-05-31 05:10:28.028665
